### ISSUE TITLE
didUpdateWidget is not working.

### ISSUE THREAD

**Issue by RahilShaikh-ios** [AurangzebHusain/one_clock#1]
When i trying to update the clock time its not working properly.
For updating the clock time i need to rebuild the whole controller.

**Comment by AurangzebHusain** [comment]
@RahilShaikh-ios  I have tested the package and find out that the didUpdateWidget is working as expected however as per your issue I figured out it was not updating the live clock neither for digital nor for analog clock. I have fixed this bug and will release a new build tomorrow. 
Thanks @RahilShaikh-ios  for letting me know.
